server:
  port: 8001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
spring:
  application:
    name: system
  cloud:
    refresh:
      refreshable: none  # 该参数是解决 spring boot 2.1.0之前版本的 相互引用导致应用不能正常启动问题
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/practice?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&connectTimeout=10000&serverTimezone=Asia/Shanghai