server:
  port: 8002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
spring:
  application:
    name: mgt

management:
  endpoints:
    web:
      exposure:
        include: "*"
